spring:
  config:
    import:
      - optional:file:env/global.env[.properties]
  spring:
    application:
      name: morning-routine-server

  profiles:
    default: dev

collector:
  us-stock:
    url: ${US_STOCK_URL}
  exchange:
    url: ${EXCHANGE_RATE_INDICATORS_URL}
  stock-indicators:
    url: ${STOCK_INDICATORS_URL}
  coin:
    url: ${COIN_INDICATORS_URL}