server:
  port: 19596

spring:
  config:
    activate:
      on-profile: dev # 환경이름설정
    import:
      - optional:file:env/dev.env[.properties]


  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 60

  jpa:
    hibernate:
      :ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    auditing:
      enabled: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

auth:
  jwt:
    secret: ${JWT_SECRET}
    access:
      exp: ${JWT_ACCESS_EXP}
    refresh:
      exp: ${JWT_REFRESH_EXP}
  otp:
    exp: ${AUTH_OTP_EXP}

logging:
  level:
    com.cookyuu.ecms_server: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
