spring:
  config:
    import:
      - optional:file:env/global.env[.properties]
  spring:
    application:
      name: morning-routine-server

  profiles:
    default: dev

collector:
  us-stock:
    url: ${US_STOCK_URL}
  exchange:
    url: ${EXCHANGE_URL}
    api-key: ${EXCHANGE_API_KEY}
    data-code: ${EXCHANGE_DATA_CODE}
  stock-indicators:
    url : ${STOCK_INDICATORS_URL}